fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Tab Characters
        entry: sh utils/check-tabs.sh
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Safety
        entry: poetry run safety check
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: poetry run mypy
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint -j 0 src/vplan tests
        pass_filenames: false
        language: system
