[tool.poetry]
name = "vplan"
version = "0.1.0"
description = "Vacation plan manager service for SmartThings"
authors = ["Kenneth J. Pronovici <pronovic@ieee.org>"]
license = "Apache-2.0"
readme = "PyPI.md"
homepage = "unset"
repository = "unset"
include = [ "Changelog", "LICENSE", "README.md", "docs", "tests", ]
packages = [ { include = "vplan", from = "src" } ]
classifiers=[
   "Programming Language :: Python :: 3",
   "License :: OSI Approved :: Apache Software License",
   "Operating System :: Unix",
   "Environment :: Console",
   "Environment :: No Input/Output (Daemon)",
   "Intended Audience :: Developers",
   "Natural Language :: English",
   "Topic :: Home Automation",
]

[tool.poetry.dependencies]
python = ">=3.7,<4"
attrs = "^20.1.0"
fastapi = "^0.70.0"
uvicorn = "^0.15.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-testdox = "^2.0.1"
coverage = "^5.0.3"
tox = "^3.14.5"
pylint = "^2.6.0"
sphinx = "^3.4.3"
toml = "^0.10.0"
pre-commit = "^2.2.0"
black = "^20.8b1"
mypy = "^0.790"
isort = "^5.0.0"
sphinx-autoapi = "^1.2.1"
safety = "^1.10.3"
coveralls = "^3.0.0"

[tool.black]
line-length = 132
target-version = ['py37', 'py38']
include = '(src\/scripts\/.*$|\.pyi?$)'
exclude = '''
/(
    \.git
  | __pycache__
  | \.tox
  | \.venv
  | build
  | dist
  | docs
  | notes
)/
'''

[tool.isort]
profile = "black"
line_length = 132
skip_glob = [ "docs", "notes" ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
