[tool.poetry]
name = "vplan"
version = "0.4.1"
description = "Vacation plan manager service for SmartThings"
authors = ["Kenneth J. Pronovici <pronovic@ieee.org>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/pronovic/vplan"
repository = "https://github.com/pronovic/vplan"
include = [
   { path = 'Changelog', format = 'sdist' },
   { path = 'LICENSE', format = 'sdist' },
   { path = 'README.md', format = 'sdist' },
   { path = 'tests', format = 'sdist' },
]
packages = [ { include = "vplan", from = "src" } ]
classifiers=[
   "Programming Language :: Python :: 3",
   "License :: OSI Approved :: Apache Software License",
   "Operating System :: Unix",
   "Environment :: Console",
   "Environment :: No Input/Output (Daemon)",
   "Intended Audience :: Developers",
   "Natural Language :: English",
   "Topic :: Home Automation",
]

[tool.poetry.scripts]
vplan = "vplan.client.cli:vplan"

[tool.poetry.dependencies]
python = ">=3.9,<4"
fastapi = "^0.70.0"
uvicorn = "^0.15.0"
pydantic-yaml = "^0.4.2"
click = "^8.1.3"
requests = "^2.27.1"
requests-unixsocket = "^0.3.0"
SQLAlchemy = "^1.4.36"
APScheduler = "^3.9.1"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-testdox = "^3.0.1"
pytest-asyncio = "^0.16.0"
coverage = "^6.3.2"
tox = "^3.25.0"
pylint = "^2.13.8"
toml = "^0.10.2"
pre-commit = "^2.18.1"
black = "^22.3.0"
mypy = "^0.950"
isort = "^5.10.1"
tzlocal = "^4.2"
busypie = "^0.4.5"
sqlalchemy2-stubs = "^0.0.2-alpha.22"
types-requests = "^2.27.25"
types-pytz = "^2021.3.7"
coveralls = "^3.3.1"

[tool.black]
line-length = 132
target-version = ['py37', 'py38']
include = '(src\/scripts\/.*$|\.pyi?$)'
exclude = '''
/(
    \.git
  | __pycache__
  | \.tox
  | \.venv
  | build
  | dist
  | docs
  | notes
)/
'''

[tool.isort]
profile = "black"
line_length = 132
skip_glob = [ "docs", "notes" ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
