database_dir: .runtime/db
database_url: sqlite+pysqlite:///.runtime/db/vplan.sqlite
scheduler:
   database_url: sqlite+pysqlite:///.runtime/db/jobs.sqlite
   thread_pool_size: 10
   daily_job:
      time: 00:30:00           # pick a time that your lights are all expected to be off
      jitter_sec: 300          # the job might run up to 300 seconds later than scheduled
      misfire_grace_sec: 1800  # if missed (i.e. if server is down), job will be run up to 30 minutes late
