# vim: set ft=yaml ts=2 sw=2 expandtab:
name: Test Suite
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  schedule:
    - cron: '05 17 15 * *'  # 15th of the month at 5:05pm UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux-build-and-test:
    name: "Linux"
    uses: pronovic/gha-shared-workflows/.github/workflows/poetry-build-and-test.yml@v3
    secrets: inherit
    with:
      matrix-os-version: "[ 'ubuntu-latest' ]"
      matrix-python-version: "[ '3.9', '3.10', '3.11', '3.12' ]"
      poetry-version: "1.6.1"
  release:
    name: "Release"
    if: github.ref_type == 'tag'
    uses: pronovic/gha-shared-workflows/.github/workflows/poetry-release.yml@v3
    needs: [ linux-build-and-test ]
    secrets: inherit
    with:
      python-version: "3.9"
      poetry-version: "1.6.1"
      publish-pypi: false
