name: Test Suite
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '05 17 15 * *'  # 15th of the month at 5:05pm UTC
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.9"]
    steps: 
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.2.1 # see https://github.com/snok/install-poetry
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install -v
      - name: Upgrade embedded tools within virtualenv
        # Safety will alert on these even though they aren't technically dependencies
        run: poetry run pip install --upgrade pip setuptools wheel
      - name: Run Tox test suite
        run: poetry run tox -c .toxrc -e "checks,coverage"
